### ISSUE TITLE
Automate renew of TLS certificate

### ISSUE THREAD

**Issue by yaakymiv** [ita-social-projects/StreetCode#1262]
create a cron job for renewing the certificate with Certbot and reloading NGINX

**Comment by MaksymukNatalia** [comment]
A cron job has been set up to renew the certificate using Certbot and reload NGINX. This is scheduled to run on the first day of each month. However, the certificate should be renewed at least once every 3 months, so if it doesn't require renewal, the job will run but the certificate will remain unchanged because it is still valid

![Image](https://github.com/ita-social-projects/StreetCode/assets/146457298/4af3dd80-a0df-45fa-bb06-af110b7c404d)
